name: Build a WAR file using Maven and Deploy Java App to Tomcat running in AWS EC2

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Tomcat Server 1
        run: |
          curl -v -u ${{ secrets.TOMCAT_HOST_1 }}:${{ secrets.TOMCAT_PASSWORD_1 }} \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_USER_1 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT&update=true"

      - name: Deploy to Tomcat Server 2
        run: |
          curl -v -u ${{ secrets.TOMCAT_HOST_2 }}:${{ secrets.TOMCAT_PASSWORD_2 }} \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_USER_2 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT&update=true"

      - name: Deploy to Tomcat Server 3
        run: |
          curl -v -u ${{ secrets.TOMCAT_HOST_3 }}:${{ secrets.TOMCAT_PASSWORD_3 }} \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_USER_3 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT&update=true"

      - name: Deploy to Tomcat Server 4
        run: |
          curl -v -u ${{ secrets.TOMCAT_HOST_$ }}:${{ secrets.TOMCAT_PASSWORD_4 }} \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_USER_4 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT&update=true"
